export const PREDEFINED_BANKS = [
  { id: 'bot', name: '臺灣銀行' },
  { id: 'landbank', name: '土地銀行' },
  { id: 'tcb', name: '合作金庫銀行' },
  { id: 'firstbank', name: '第一銀行' },
  { id: 'hncb', name: '華南銀行' },
  { id: 'chb', name: '彰化銀行' },
  { id: 'shanghai', name: '上海商業儲蓄銀行' },
  { id: 'fubon', name: '富邦銀行' },
  { id: 'cathay', name: '國泰世華銀行' },
  { id: 'kaohsiung', name: '高雄銀行' },
  { id: 'mega', name: '兆豐銀行' },
  { id: 'o-bank', name: '王道銀行' },
  { id: 'tbb', name: '臺灣中小企業銀行' },
  { id: 'scb', name: '渣打銀行' },
  { id: 'taichung', name: '台中銀行' },
  { id: 'ktb', name: '京城銀行' },
  { id: 'hsbc', name: '滙豐銀行' },
  { id: 'taipeistar', name: '瑞興銀行' },
  { id: 'hwatai', name: '華泰銀行' },
  { id: 'skbank', name: '新光銀行' },
  { id: 'sunnybank', name: '陽信銀行' },
  { id: 'bop', name: '板信銀行' },
  { id: 'cotabank', name: '三信銀行' },
  { id: 'post', name: '中華郵政' },
  { id: 'union', name: '聯邦銀行' },
  { id: 'feib', name: '遠東銀行' },
  { id: 'yuanta', name: '元大銀行' },
  { id: 'sinopac', name: '永豐銀行' },
  { id: 'esun', name: '玉山銀行' },
  { id: 'kgi', name: '凱基銀行' },
  { id: 'dbs', name: '星展銀行' },
  { id: 'taishin', name: '台新銀行' },
  { id: 'entitie', name: '安泰銀行' },
  { id: 'ctbc', name: '中國信託銀行' },
  { id: 'nextbank', name: '將來銀行' },
  { id: 'linebank', name: '連線銀行' },
  { id: 'rakuten', name: '樂天銀行' },
];

export const PREDEFINED_EPAYS = [
  { id: 'linepay', name: 'LINE Pay' },
  { id: 'linepaymoney', name: 'LINE Pay Money' },
  { id: 'ipassmoney', name: 'iPass Money' }, // Clarified
  { id: 'jkopay', name: '街口支付' },
  { id: 'taiwanpay', name: '台灣 Pay' },
  { id: 'applepay', name: 'Apple Pay' },
  { id: 'googlepay', name: 'Google Pay' },
  { id: 'samsungpay', name: 'Samsung Pay' },
  { id: 'garminpay', name: 'Garmin Pay' },
  { id: 'easywallet', name: '悠遊付' },
  { id: 'icashpay', name: 'icash Pay' },
  { id: 'pxpay', name: '全支付' },
  { id: 'piwallet', name: 'Pi 拍錢包' },
  { id: 'famiplus', name: '全盈+PAY' },
  { id: 'zingala', name: 'zingala 銀角零卡' },
  { id: 'paypal', name: 'PayPal' },
];

export const PREDEFINED_CARDS = [
  { id: 'creditcard', name: '信用卡' },
  { id: 'easycard', name: '悠遊卡' },
  { id: 'ipass', name: '一卡通' },
  { id: 'icash', name: 'icash 2.0' },
];

export const DEFAULT_CATEGORIES = [
  { id: 'food', name: '餐飲', type: 'expense', icon: 'utensils', isCustom: false },
  { id: 'transport', name: '交通', type: 'expense', icon: 'train', isCustom: false },
  { id: 'shopping', name: '購物', type: 'expense', icon: 'shopping-bag', isCustom: false },
  { id: 'entertainment', name: '娛樂', type: 'expense', icon: 'film', isCustom: false },
  { id: 'bills', name: '帳單與水電', type: 'expense', icon: 'zap', isCustom: false },
  { id: 'health', name: '醫療與健康', type: 'expense', icon: 'heart', isCustom: false },

  { id: 'salary', name: '薪資', type: 'income', icon: 'banknote', isCustom: false },
  { id: 'investment', name: '投資', type: 'income', icon: 'trending-up', isCustom: false },
  { id: 'other_income', name: '其他收入', type: 'income', icon: 'plus-circle', isCustom: false },
];
